[serve]
addreess = "127.0.0.1"
port = 8081

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = [
    "-c", "npx sass ./src/styles/main.scss ./dist/main.css && npx tailwindcss -i ./dist/main.css -o ./src/styles/global.css --minify"
]

[watch]
ignore = ["src/styles/global.css"]